import { redirect } from 'next/navigation';
import dbConnect from '@/lib/mongodb';
import AttendanceRecord from '@/models/AttendanceRecord';
import Course from '@/models/Course';
import { getSessionUser } from '@/lib/auth';
import { StudentNavbar } from './components';

export const dynamic = 'force-dynamic';

export default async function StudentDashboardPage() {
  const user = await getSessionUser();

  if (!user) {
    redirect('/login');
  }

  if (user.role !== 'STUDENT') {
    redirect('/dashboard/lecturer');
  }

  await dbConnect();

  const records = await AttendanceRecord.find({ studentId: user._id })
    .populate({
      path: 'courseId',
      model: Course,
    })
    .sort({ markedAt: -1 });

  const totalAttendance = records.length;

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-955 flex flex-col">
      <StudentNavbar userName={user.name} userEmail={user.email} />

      <main className="flex-1 mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="mb-8 flex flex-col gap-2">
          <h1 className="text-3xl font-extrabold tracking-tight text-zinc-900 dark:text-white">
            Student Dashboard
          </h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            Track your classes attended and scan QR codes from your instructors to record attendance.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 mb-10">
          <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
            <p className="text-xs font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-1">
              Personal Information
            </p>
            <h3 className="text-xl font-bold text-zinc-900 dark:text-white">
              {user.name}
            </h3>
            <p className="text-sm text-zinc-500 mt-0.5">
              {user.email}
            </p>
          </div>

          <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
            <p className="text-xs font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-1">
              Total Classes Attended
            </p>
            <p className="text-3xl font-extrabold text-purple-600 dark:text-purple-450">
              {totalAttendance}
            </p>
          </div>
        </div>

        <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
          <h2 className="text-xl font-bold text-zinc-900 dark:text-white mb-6">
            Recent Attendance History
          </h2>

          {records.length === 0 ? (
            <div className="rounded-xl border border-dashed border-zinc-200 dark:border-zinc-800 p-12 text-center bg-zinc-50/20 dark:bg-zinc-900/20">
              <svg className="mx-auto h-12 w-12 text-zinc-300 dark:text-zinc-700 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
              </svg>
              <h3 className="text-sm font-semibold text-zinc-900 dark:text-white mb-1">
                No attendance logs found
              </h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-450 max-w-xs mx-auto">
                Scan attendance QR codes generated by your lecturer to log check-ins.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead>
                  <tr className="border-b border-zinc-200 dark:border-zinc-800 text-zinc-400 font-semibold">
                    <th className="pb-3 pr-4">Course Code</th>
                    <th className="pb-3 px-4">Course Title</th>
                    <th className="pb-3 pl-4">Date & Time Marked</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-150 dark:divide-zinc-850">
                  {records.map((record) => (
                    <tr key={record._id.toString()} className="text-zinc-800 dark:text-zinc-200">
                      <td className="py-4 pr-4 font-semibold text-indigo-600 dark:text-indigo-400">
                        {record.courseId?.code || 'N/A'}
                      </td>
                      <td className="py-4 px-4 font-medium">
                        {record.courseId?.title || 'Unknown Course'}
                      </td>
                      <td className="py-4 pl-4 text-zinc-500 dark:text-zinc-400 text-xs">
                        {new Date(record.markedAt).toLocaleDateString()} at{' '}
                        {new Date(record.markedAt).toLocaleTimeString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
