import { redirect } from 'next/navigation';
import dbConnect from '@/lib/mongodb';
import AttendanceRecord from '@/models/AttendanceRecord';
import Course from '@/models/Course';
import AttendanceSession from '@/models/AttendanceSession';
import { getSessionUser } from '@/lib/auth';
import { StudentNavbar, StudentHistoryTable } from './components';

export const dynamic = 'force-dynamic';

export default async function StudentDashboardPage() {
  const user = await getSessionUser();

  if (!user) {
    redirect('/login');
  }

  if (user.role !== 'STUDENT') {
    redirect('/dashboard/lecturer');
  }

  await dbConnect();

  const records = await AttendanceRecord.find({ studentId: user._id })
    .populate({
      path: 'courseId',
      model: Course,
    })
    .sort({ markedAt: -1 });

  const totalAttendance = records.length;

  const courses = await Course.find({}).sort({ code: 1 });
  const coursesWithAttendance = await Promise.all(
    courses.map(async (course) => {
      const totalSessions = await AttendanceSession.countDocuments({ courseId: course._id });
      const attendedSessions = await AttendanceRecord.countDocuments({
        courseId: course._id,
        studentId: user._id,
      });
      const percentage = totalSessions > 0 ? Math.round((attendedSessions / totalSessions) * 100) : null;
      const displayPercentage = percentage !== null ? Math.min(percentage, 100) : 0;
      return {
        _id: course._id.toString(),
        code: course.code,
        title: course.title,
        totalSessions,
        attendedSessions,
        percentage: displayPercentage,
      };
    })
  );

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-black flex flex-col">
      <StudentNavbar userName={user.name} userEmail={user.email} />

      <main className="flex-1 mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="mb-8 flex flex-col gap-2">
          <h1 className="text-3xl font-extrabold tracking-tight text-zinc-900 dark:text-white">
            Student Dashboard
          </h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            Track your classes attended and scan QR codes from your instructors to record attendance.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 mb-10">
          <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
            <p className="text-xs font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-1">
              Personal Information
            </p>
            <h3 className="text-xl font-bold text-zinc-900 dark:text-white">
              {user.name}
            </h3>
            <div className="mt-1.5 flex flex-wrap gap-x-4 gap-y-1 text-xs font-semibold text-zinc-500">
              <span>{user.email}</span>
              <span className="text-zinc-300 dark:text-zinc-700">•</span>
              <span className="font-mono text-zinc-700 dark:text-zinc-300">MATRIC: {user.matricNo || 'N/A'}</span>
            </div>
          </div>

          <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
            <p className="text-xs font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-1">
              Total Classes Attended
            </p>
            <p className="text-3xl font-extrabold text-zinc-900 dark:text-white">
              {totalAttendance}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
          <div className="lg:col-span-2">
            <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <h2 className="text-xl font-bold text-zinc-900 dark:text-white mb-6">
                Recent Attendance History
              </h2>

              {records.length === 0 ? (
                <div className="rounded-xl border border-dashed border-zinc-200 dark:border-zinc-800 p-12 text-center bg-zinc-50/20 dark:bg-zinc-900/20">
                  <svg className="mx-auto h-12 w-12 text-zinc-300 dark:text-zinc-700 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                  </svg>
                  <h3 className="text-sm font-semibold text-zinc-900 dark:text-white mb-1">
                    No attendance logs found
                  </h3>
                  <p className="text-sm text-zinc-500 dark:text-zinc-455 max-w-xs mx-auto">
                    Scan attendance QR codes generated by your lecturer to log check-ins.
                  </p>
                </div>
              ) : (
                <StudentHistoryTable records={JSON.parse(JSON.stringify(records))} />
              )}
            </div>
          </div>

          <div className="lg:col-span-1">
            <div className="rounded-2xl border border-zinc-200/40 dark:border-zinc-800/40 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <h2 className="text-xl font-bold text-zinc-900 dark:text-white mb-6">
                Course Attendance
              </h2>

              {coursesWithAttendance.length === 0 ? (
                <p className="text-sm text-zinc-500 dark:text-zinc-450 py-4 text-center">
                  No courses available.
                </p>
              ) : (
                <div className="space-y-4">
                  {coursesWithAttendance.map((item) => (
                    <div key={item._id} className="pb-4 border-b border-zinc-100 dark:border-zinc-800 last:border-b-0 last:pb-0">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <span className="inline-flex items-center rounded bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 text-[10px] font-mono font-semibold text-zinc-750 dark:text-zinc-300 border border-zinc-200 dark:border-zinc-700">
                            {item.code}
                          </span>
                          <h4 className="text-sm font-semibold text-zinc-900 dark:text-white mt-1.5 line-clamp-1">
                            {item.title}
                          </h4>
                        </div>
                        <div className="text-right shrink-0 ml-4">
                          <span className="text-sm font-bold text-zinc-900 dark:text-white">
                            {item.totalSessions > 0 ? `${item.percentage}%` : 'N/A'}
                          </span>
                          <p className="text-[10px] text-zinc-400 mt-0.5 font-medium">
                            {item.attendedSessions} / {item.totalSessions} classes
                          </p>
                        </div>
                      </div>
                      {item.totalSessions > 0 && (
                        <div className="w-full bg-zinc-100 dark:bg-zinc-850 h-1.5 rounded-full overflow-hidden border border-zinc-200/30 dark:border-zinc-800/30">
                          <div 
                            className="bg-black dark:bg-white h-full rounded-full transition-all duration-300" 
                            style={{ width: `${item.percentage}%` }}
                          />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

